#' @title Turn birth date into month number since 'Month1'
#'
#' @description For species that breed multiple times per year and/or with a age
#' of first reproduction of less than a year, one cannot work with birth year in 
#' \code{sequoia}. The month number, e.g. since January 2000, can often be used
#' instead. 
#'
#' @param BirthDate  either a named vector with dates (YY-MM-DD), or a matrix 
#'  with columns YY (year) and MM (month) and with IDs as rownames.
#' @param Year1  starting year
#' @param Month1  starting month  
#'
#' @return a named vector with month numbers since Year1-Month1. 
#'
#' @examples
#' BirthDate <- c('Yellow' = '2004-03-12', 'Green' = '2006-12-24', 'Red'='2005-01-08')
#' BirthDate2MonthNumber(BirthDate)  

BirthDate2MonthNumber <- function(BirthDate,
                                  Year1 = 2000,
                                  Month1 = 1) 
{
  if (inherits(BirthDate, 'matrix')) {
    IDs <- rownames(BirthDate)
    B.Year <- BirthDate[,1] - Year1
    B.Month <- BirthDate[,2] - Month1 +1
  } else {
    BirthDate <- as.Date(BirthDate)
    IDs <- names(BirthDate)
    B.Year <- as.numeric(format(BirthDate, '%Y')) - Year1
    B.Month <- as.numeric(format(BirthDate, '%m')) - Month1 +1
  }
  if (any(B.Year) < 0)  stop('Some BirthDates are before Year1')
  
  Month.num <- 12*B.Year + B.Month
  
  names(Month.num) <- IDs
  return(Month.num)
}





################################################################################
################################################################################
################################################################################

#' @title Reverse \code{BirthDate2MonthNumber}
#'
#' @description Turn month numbers as generated by \code{BirthDate2MonthNumber}
#' back into calendar year + month. The same \code{Year1} and \code{Month1} must
#' be used!
#'
#' @param MonthNumber a named vector with month numbers since Year1-Month1. 
#' @param Year1  starting year
#' @param Month1  starting month  
#'
#' @return a matrix with columns YY and MM, with IDs in rownames. 
#' 

MonthNumber2BirthDate <- function(MonthNumber,
                                  Year1 = 2000,
                                  Month1 = 1) 
{
  B.Year <- floor( (MonthNumber-1)/12 ) + Year1
  B.Month <- (MonthNumber-1) %% 12 + Month1
  
  # when Month1 >1, some may need to shift to next calendar year
  NextYear <- B.Month > 12
  B.Year[NextYear] <- B.Year[NextYear] +1
  B.Month[NextYear] <- B.Month[NextYear] -12
  
  BirthDate <- cbind(YY = B.Year,
                     MM = B.Month)
  rownames(BirthDate) <- names(MonthNumber)
  
  return(BirthDate)
}
